#dataset: cifar10
#dataset: cifar100
dataset: ImageNet16-120
experiment_type: search
out_dir: p201-0
predictor: gcn
search_space: nasbench201
max_acc: 46.766
seed: 1
uniform_random: 1
search_device: 'cuda:0'
surrogate_device: 'cuda:0'
dataset_ver: v1_0
num_vertices: 8
sample_mean: False
hw_target_name: edgegpu_latency
#hw_target_name: raspi4_latency
#hw_target_name: edgetpu_latency
#hw_target_name: pixel3_latency
#hw_target_name: eyeriss_latency
#hw_target_name: fpga_latency
model_fit_para:
  {
      gcn_hidden: 256,
      gcn_layers: 2,
      mlp_hidden: 256,
      batch_size: 20,
      lr: 0.005,
      model_epochs: 400,
      ranking_loss_reg_coe: 0.2,
      lr_gamma: 0.9,
      lr_step: 10,
      log_step: 10,
      weighted_pooling: False
  }
config_name: "acc_0516_c10"
test_id: 0
#in_progress_sampling: False
#dynamic_verify_ratio: False
#ranking_Loss_ratio: 0
ylim_s: 44
ylim_e: 48
search_para:
  {
    base_temp: 0.7,
    min_temp: 0.2,
    num_nodes: 6,
    num_ops: 5,
    lr: 0.05,
    lr_step: 10,
    lr_gamma: 0.9,
    log_step: 10,
    lhs_lower: 0.0,
    lhs_range: 2.0,
    std_ratio: 0.0,
    std_decay: 0.75,
    init_adj_change: 0.5,
    lr_beta: 0.001,
    input_batch_size: 20,
    num_input_group: 1,
    num_sample_each_step: 10,
    num_sample_init: 20,
    object_scaler: [1, 0],
    object_scaler_step: 0.0,
    similarity_penalty_ratio: 0,
    similarity_penalty_decay: 0.6,
    search_steps: 8,
    low_fi_top_k: 5,
    verify_ratio: 30,
    acq_fun: 'min',   # {'mean', 'min', 'max', 'ucb', 'ei'}
    valid_freq: 2,
    search_epochs: 100,
    low_fi_epoch: 200,
    low_fi_mean_window: 1
  }

condition:
  {
    max_flops: 700,
    max_latency: 2,
    max_params: 21,
    over_latency_ratio: 0.3,
    max_latency_scaler: 1.4
  }

mean: 45.79289026660551
std: 9.242084621603457
latency_mean: 5.040258225097657
latency_std: 1.524556024319693