dataset: cifar10
experiment_type: search
out_dir: p101-0
predictor: gcn
search_space: nasbench101
max_acc: 95.05
seed: 2
search_device: 'cpu'
surrogate_device: 'cpu'
dataset_ver: None
uniform_random: 1
num_vertices: 7
sample_mean: True
config_name: "test_101"
test_id: 0
ylim_s: 93
ylim_e: 96
model_fit_para:
  {
      gcn_hidden: 186,
      gcn_layers: 2,
      mlp_hidden:  186,
      batch_size: 10,
      lr: 0.001,
      model_epochs: 500,
      ranking_loss_reg_coe: 0.2,
      lr_gamma: 0.92,
      lr_step: 10,
      log_step: 10,
      weighted_pooling: False
  }
search_para:
  {
    base_temp: 0.7,
    min_temp: 0.2,
    num_nodes: 5,
    num_ops: 3,
    lr: 0.01,
    lr_step: 10,
    lr_gamma: 0.9,
    log_step: 10,
    lhs_lower: 0.5,
    lhs_range: 1.0,
    init_adj_change: 0.5,
    lr_beta: 0.01,
    input_batch_size: 2, # parallel_batch
    num_sample_each_step: 10,
    num_sample_init: 10,
    search_steps: 14,
    verify_ratio: 40,
    valid_freq: 2,
    search_epochs: 200,
  }
# test
mean: 89.78164079785347
std: 4.3381662039682585

