#dataset: cifar10
dataset: cifar100
#dataset: ImageNet16-120
experiment_type: search
out_dir: p201-0
predictor: gcn
search_space: nasbench201
max_acc: 73.493
seed: 1
uniform_random: 1
search_device: 'cpu'
surrogate_device: 'cuda:0'
dataset_ver: v1_0
num_vertices: 8
sample_mean: False
config_name: "acc_0516_c10"
test_id: 0
ylim_s: 68
ylim_e: 75
model_fit_para:
  {
      gcn_hidden: 128,
      gcn_layers: 2,
      mlp_hidden: 128,
      batch_size: 20,
      lr: 0.002,
      model_epochs: 100,
      ranking_loss_reg_coe: 0.2,
      lr_gamma: 0.9,
      lr_step: 10,
      log_step: 10,
      weighted_pooling: False
  }
search_para:
  {
    base_temp: 0.7,
    min_temp: 0.2,
    num_nodes: 6,
    num_ops: 5,
    lr: 0.05,
    lr_step: 10,
    lr_gamma: 0.9,
    log_step: 10,
    lhs_lower: 0.0,
    lhs_range: 2.0,
    init_adj_change: 0.5,
    lr_beta: 0.001,
    input_batch_size: 20,
    num_sample_each_step: 5,
    num_sample_init: 10,
    search_steps: 18,
    verify_ratio: 20,
    valid_freq: 2,
    search_epochs: 100
  }

mean: 61.28174504349649
std: 12.142806312757774